export const LANGUAGES = [
  { code: "fr", label: "Francais" },
  { code: "en", label: "English" },
  { code: "ar", label: "العربية" },
];

const STRINGS = {
  en: {
    appName: "AgroVision Olive",
    tagline: "Premium Olive Farm Intelligence",
    landingTitle: "Manage your olive farm with trustworthy AI insights",
    landingBody:
      "AgroVision Olive combines harvest timing, disease scanning, and production forecasting in one professional dashboard built for real farm decisions.",
    startSetup: "Start Farm Setup",
    openDashboard: "Open Dashboard",
    tryTools: "Try AI Tools",
    oliveDetect: "Olive Detect",
    harvestTime: "Harvest Time",
    diseaseScan: "Disease Scan",
    preliminary: "Preliminary result",
    needsReview: "Needs review",
    highConfidence: "High confidence",
    navDashboard: "Dashboard",
    navHarvestTime: "Harvest Time",
    navDiseaseScan: "Disease Scan",
    navProductionModel: "Production Model",
    navAssistant: "Assistant",
    navFarmSetup: "Farm Setup",
    navHome: "Home",
    navSignIn: "Sign in",
    navCreateAccount: "Create account",
    quickHarvestReport: "Harvest Report",
    quickScanLeaf: "Scan Leaf",
  },
  fr: {
    appName: "AgroVision Olive",
    tagline: "Intelligence premium pour oliveraie",
    landingTitle: "Gerez votre ferme d'oliviers avec des insights IA fiables",
    landingBody:
      "AgroVision Olive combine prediction de recolte, scan maladie et prevision de production dans un tableau de bord professionnel.",
    startSetup: "Demarrer configuration",
    openDashboard: "Ouvrir dashboard",
    tryTools: "Essayer outils IA",
    oliveDetect: "Detection d'olives",
    harvestTime: "Prediction recolte",
    diseaseScan: "Scan maladie",
    preliminary: "Resultat preliminaire",
    needsReview: "A verifier",
    highConfidence: "Confiance elevee",
    navDashboard: "Tableau de bord",
    navHarvestTime: "Harvest Time",
    navDiseaseScan: "Scan maladie",
    navProductionModel: "Modele de production",
    navAssistant: "Assistant",
    navFarmSetup: "Configuration ferme",
    navHome: "Accueil",
    navSignIn: "Connexion",
    navCreateAccount: "Creer un compte",
    quickHarvestReport: "Rapport de recolte",
    quickScanLeaf: "Scanner feuille",
  },
  ar: {
    appName: "AgroVision Olive",
    tagline: "ذكاء موثوق لمزارع الزيتون",
    landingTitle: "ادِر مزرعة الزيتون الخاصة بك بمساعدة ذكاء اصطناعي موثوق",
    landingBody:
      "يجمع AgroVision Olive بين تقدير الحصاد، فحص الأمراض، وتوقع الإنتاج داخل لوحة تحكم واحدة.",
    startSetup: "ابدأ الإعداد",
    openDashboard: "افتح لوحة التحكم",
    tryTools: "جرّب أدوات الذكاء الاصطناعي",
    oliveDetect: "كشف الزيتون",
    harvestTime: "توقيت الحصاد",
    diseaseScan: "فحص المرض",
    preliminary: "نتيجة أولية",
    needsReview: "تحتاج إلى مراجعة",
    highConfidence: "ثقة عالية",
    navDashboard: "لوحة التحكم",
    navHarvestTime: "توقيت الحصاد",
    navDiseaseScan: "فحص المرض",
    navProductionModel: "نموذج الإنتاج",
    navAssistant: "المساعد",
    navFarmSetup: "إعداد المزرعة",
    navHome: "الرئيسية",
    navSignIn: "تسجيل الدخول",
    navCreateAccount: "إنشاء حساب",
    quickHarvestReport: "تقرير الحصاد",
    quickScanLeaf: "فحص الورقة",
  },
};

export function t(language, key) {
  const bucket = STRINGS[language] || STRINGS.en;
  return bucket[key] || STRINGS.en[key] || key;
}
